networks:
  smatech:
    external: true

services:
  eureka-server:
    image: smatech-eureka:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    networks:
      - smatech
    ports:
      - "8761:8761"
    restart: always
